CREATE TABLE permissions (
    id VARCHAR(255) PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(50) NOT NULL,
    permission_id VARCHAR(255) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions (id),
    CONSTRAINT uq_role_permission UNIQUE (role, permission_id)
);

-- Seed Base Permissions
INSERT INTO permissions (id, description) VALUES ('MANAGE_USERS', 'Create, update, and manage system users');
INSERT INTO permissions (id, description) VALUES ('MANAGE_SYSTEM', 'Access and modify system configuration and master data');
INSERT INTO permissions (id, description) VALUES ('VIEW_ALL_PROJECTS', 'View all projects across the organization');
INSERT INTO permissions (id, description) VALUES ('MANAGE_LEAVES', 'Approve or reject leave requests');
INSERT INTO permissions (id, description) VALUES ('MANAGE_REVIEWS', 'Create and edit performance reviews');

-- Default mappings for ADMIN (All enabled)
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('ADMIN', 'MANAGE_USERS', TRUE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('ADMIN', 'MANAGE_SYSTEM', TRUE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('ADMIN', 'VIEW_ALL_PROJECTS', TRUE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('ADMIN', 'MANAGE_LEAVES', TRUE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('ADMIN', 'MANAGE_REVIEWS', TRUE);

-- Default mappings for MANAGER
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('MANAGER', 'MANAGE_USERS', FALSE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('MANAGER', 'MANAGE_SYSTEM', FALSE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('MANAGER', 'VIEW_ALL_PROJECTS', TRUE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('MANAGER', 'MANAGE_LEAVES', TRUE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('MANAGER', 'MANAGE_REVIEWS', TRUE);

-- Default mappings for EMPLOYEE
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('EMPLOYEE', 'MANAGE_USERS', FALSE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('EMPLOYEE', 'MANAGE_SYSTEM', FALSE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('EMPLOYEE', 'VIEW_ALL_PROJECTS', FALSE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('EMPLOYEE', 'MANAGE_LEAVES', FALSE);
INSERT INTO role_permissions (role, permission_id, is_enabled) VALUES ('EMPLOYEE', 'MANAGE_REVIEWS', FALSE);
