CREATE TABLE master_data (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category      VARCHAR(50)  NOT NULL,
    code          VARCHAR(50)  NOT NULL,
    label         VARCHAR(100) NOT NULL,
    display_order INT          NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_master_data_category_code UNIQUE (category, code)
);

CREATE INDEX idx_master_data_category ON master_data(category);
